package edu.uva.liftlab.pilot.util;

public enum PropertyType {
    BLACK_PILOTFUNC_LIST,
    WHITE_PILOTFUNC_LIST,
    MANUAL_INSTRUMENTATION,
    START_POINTS,
    TRACE_CLASSES,
    HTTP_SEND_CLASSES,
    HTTP_RECV_CLASSES,
    RPC_CLASSES,
    ISOLATE_CLASSES,
    IO_CLASSES,
    SEDA_QUEUE,
    SEDA_WORKER,
    ENTRY_CLASS,
    STATE_BW_ENABLED,
    STATE_BLACKLIST_CLASS,
    STATE_WHITELIST_CLASS,
    CTX_TREE_BLACK_LIST,
    SIMPLE_INSTRUMENTATION,
    TRACK_INIT_CLASSES
}
